# Generated by Django 5.1 on 2024-09-17 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='planet',
            fields=[
                ('planetID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=50)),
                ('detImg', models.CharField(max_length=50)),
                ('detDes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cons_period',
            fields=[
                ('reqID', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateSave', models.DateField(null=True)),
                ('dateFinish', models.DateField(null=True)),
                ('isDraft', models.BooleanField(default=True)),
                ('isSaved', models.BooleanField(default=False)),
                ('isAccepted', models.BooleanField(null=True)),
                ('isCanceled', models.BooleanField(null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('dateStart', models.DateField(null=True)),
                ('dateEnd', models.DateField(null=True)),
                ('constellation', models.TextField(max_length=50, null=True)),
                ('moderID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_reqs', to=settings.AUTH_USER_MODEL)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNew', models.BooleanField(null=True)),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='astro_app.cons_period')),
                ('planetID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='astro_app.planet')),
            ],
            options={
                'unique_together': {('planetID', 'reqID')},
            },
        ),
    ]
