# Generated by Django 5.1 on 2024-09-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0002_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cons_period',
            name='moderID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_reqs', to='astro_app.authuser'),
        ),
        migrations.AlterField(
            model_name='cons_period',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reqs', to='astro_app.authuser'),
        ),
    ]
