# Generated by Django 5.1 on 2024-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0003_alter_cons_period_moderid_alter_cons_period_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='detImg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
