# Generated by Django 5.1 on 2024-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0004_alter_planet_detimg_alter_planet_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cons_period',
            name='isAccepted',
        ),
        migrations.RemoveField(
            model_name='cons_period',
            name='isCanceled',
        ),
        migrations.RemoveField(
            model_name='cons_period',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='cons_period',
            name='isDraft',
        ),
        migrations.RemoveField(
            model_name='cons_period',
            name='isSaved',
        ),
        migrations.AddField(
            model_name='cons_period',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
    ]
