# Generated by Django 5.1 on 2024-10-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0005_remove_cons_period_isaccepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='detImg',
        ),
    ]
