# Generated by Django 5.1 on 2024-10-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_app', '0006_remove_planet_detimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cons_period',
            old_name='dateCreate',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='cons_period',
            old_name='dateFinish',
            new_name='dateModerated',
        ),
        migrations.RenameField(
            model_name='cons_period',
            old_name='dateSave',
            new_name='dateSaved',
        ),
    ]
