# Generated by Django 5.1 on 2024-09-12 13:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='planets',
            fields=[
                ('planetID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=50)),
                ('detImg', models.CharField(max_length=50)),
                ('detDes', models.TextField()),
                ('constellations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('transferDates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('reqID', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('dateFinished', models.DateField()),
                ('isDraft', models.BooleanField(default=False)),
                ('isSaved', models.BooleanField(default=False)),
                ('isAccepted', models.BooleanField(default=False)),
                ('isCanceled', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='mm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curConstellation', models.TextField()),
                ('planetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astro.planets')),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astro.requests')),
            ],
            options={
                'unique_together': {('planetID', 'reqID')},
            },
        ),
    ]
