# Generated by Django 5.1 on 2024-09-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_requests_moderid_requests_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planets',
            old_name='transferDates',
            new_name='transfer_dates',
        ),
    ]
