# Generated by Django 5.1 on 2024-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0003_rename_transferdates_planets_transfer_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='constellations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='transfer_dates',
            field=models.TextField(null=True),
        ),
    ]
