# Generated by Django 5.1 on 2024-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0005_alter_requests_datefinished_alter_requests_isdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='dateObs',
            field=models.DateField(null=True),
        ),
    ]
